services:
  - type: web
    name: notes-app-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: FASTAPI_URL
        value: "THE_LIVE_URL_OF_YOUR_FAST_API_SERVICE"
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: MONGODB_URI
        sync: false

  - type: web
    name: fast-api-service
    runtime: python
    region: oregon
    plan: free
    rootDir: fast_api
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false