services:
  - type: web
    name: notes-app-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: FASTAPI_SUMMARIZE_URL
        sync: false
      - key: FASTAPI_INTERNAL_KEY
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: MONGO_URI
        sync: false

  - type: web
    name: fast-api-service
    runtime: python
    region: oregon
    plan: free
    rootDir: fast_api
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/health"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: FASTAPI_INTERNAL_KEY
        sync: false
